//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};

pub const TRANSFER_CREATOR_FEES_TO_PUMP_DISCRIMINATOR: [u8; 8] =
    [139, 52, 134, 85, 228, 229, 108, 241];

/// Accounts.
#[derive(Debug)]
pub struct TransferCreatorFeesToPump {
    /// Pump Canonical Pool are quoted in wSOL
    pub wsol_mint: solana_pubkey::Pubkey,

    pub token_program: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub associated_token_program: solana_pubkey::Pubkey,

    pub coin_creator: solana_pubkey::Pubkey,

    pub coin_creator_vault_authority: solana_pubkey::Pubkey,

    pub coin_creator_vault_ata: solana_pubkey::Pubkey,

    pub pump_creator_vault: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl TransferCreatorFeesToPump {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.wsol_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.coin_creator,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.coin_creator_vault_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.coin_creator_vault_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pump_creator_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = TransferCreatorFeesToPumpInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::PUMP_AMM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TransferCreatorFeesToPumpInstructionData {
    discriminator: [u8; 8],
}

impl TransferCreatorFeesToPumpInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [139, 52, 134, 85, 228, 229, 108, 241],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> { borsh::to_vec(self) }
}

impl Default for TransferCreatorFeesToPumpInstructionData {
    fn default() -> Self { Self::new() }
}

/// Instruction builder for `TransferCreatorFeesToPump`.
///
/// ### Accounts:
///
///   0. `[]` wsol_mint
///   1. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   2. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   3. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
///   4. `[]` coin_creator
///   5. `[writable]` coin_creator_vault_authority
///   6. `[writable]` coin_creator_vault_ata
///   7. `[writable]` pump_creator_vault
///   8. `[]` event_authority
///   9. `[]` program
#[derive(Clone, Debug, Default)]
pub struct TransferCreatorFeesToPumpBuilder {
    wsol_mint: Option<solana_pubkey::Pubkey>,
    token_program: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    associated_token_program: Option<solana_pubkey::Pubkey>,
    coin_creator: Option<solana_pubkey::Pubkey>,
    coin_creator_vault_authority: Option<solana_pubkey::Pubkey>,
    coin_creator_vault_ata: Option<solana_pubkey::Pubkey>,
    pump_creator_vault: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl TransferCreatorFeesToPumpBuilder {
    pub fn new() -> Self { Self::default() }

    /// Pump Canonical Pool are quoted in wSOL
    #[inline(always)]
    pub fn wsol_mint(&mut self, wsol_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.wsol_mint = Some(wsol_mint);
        self
    }

    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }

    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }

    /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.associated_token_program = Some(associated_token_program);
        self
    }

    #[inline(always)]
    pub fn coin_creator(&mut self, coin_creator: solana_pubkey::Pubkey) -> &mut Self {
        self.coin_creator = Some(coin_creator);
        self
    }

    #[inline(always)]
    pub fn coin_creator_vault_authority(
        &mut self,
        coin_creator_vault_authority: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.coin_creator_vault_authority = Some(coin_creator_vault_authority);
        self
    }

    #[inline(always)]
    pub fn coin_creator_vault_ata(
        &mut self,
        coin_creator_vault_ata: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.coin_creator_vault_ata = Some(coin_creator_vault_ata);
        self
    }

    #[inline(always)]
    pub fn pump_creator_vault(&mut self, pump_creator_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.pump_creator_vault = Some(pump_creator_vault);
        self
    }

    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }

    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }

    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }

    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = TransferCreatorFeesToPump {
            wsol_mint: self.wsol_mint.expect("wsol_mint is not set"),
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
            associated_token_program: self.associated_token_program.unwrap_or(
                solana_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
            ),
            coin_creator: self.coin_creator.expect("coin_creator is not set"),
            coin_creator_vault_authority: self
                .coin_creator_vault_authority
                .expect("coin_creator_vault_authority is not set"),
            coin_creator_vault_ata: self
                .coin_creator_vault_ata
                .expect("coin_creator_vault_ata is not set"),
            pump_creator_vault: self
                .pump_creator_vault
                .expect("pump_creator_vault is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `transfer_creator_fees_to_pump` CPI accounts.
pub struct TransferCreatorFeesToPumpCpiAccounts<'a, 'b> {
    /// Pump Canonical Pool are quoted in wSOL
    pub wsol_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator_vault_authority: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator_vault_ata: &'b solana_account_info::AccountInfo<'a>,

    pub pump_creator_vault: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `transfer_creator_fees_to_pump` CPI instruction.
pub struct TransferCreatorFeesToPumpCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Pump Canonical Pool are quoted in wSOL
    pub wsol_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator_vault_authority: &'b solana_account_info::AccountInfo<'a>,

    pub coin_creator_vault_ata: &'b solana_account_info::AccountInfo<'a>,

    pub pump_creator_vault: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> TransferCreatorFeesToPumpCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: TransferCreatorFeesToPumpCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            wsol_mint: accounts.wsol_mint,
            token_program: accounts.token_program,
            system_program: accounts.system_program,
            associated_token_program: accounts.associated_token_program,
            coin_creator: accounts.coin_creator,
            coin_creator_vault_authority: accounts.coin_creator_vault_authority,
            coin_creator_vault_ata: accounts.coin_creator_vault_ata,
            pump_creator_vault: accounts.pump_creator_vault,
            event_authority: accounts.event_authority,
            program: accounts.program,
        }
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }

    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }

    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.wsol_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.coin_creator.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.coin_creator_vault_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.coin_creator_vault_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pump_creator_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = TransferCreatorFeesToPumpInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::PUMP_AMM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.wsol_mint.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.associated_token_program.clone());
        account_infos.push(self.coin_creator.clone());
        account_infos.push(self.coin_creator_vault_authority.clone());
        account_infos.push(self.coin_creator_vault_ata.clone());
        account_infos.push(self.pump_creator_vault.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `TransferCreatorFeesToPump` via CPI.
///
/// ### Accounts:
///
///   0. `[]` wsol_mint
///   1. `[]` token_program
///   2. `[]` system_program
///   3. `[]` associated_token_program
///   4. `[]` coin_creator
///   5. `[writable]` coin_creator_vault_authority
///   6. `[writable]` coin_creator_vault_ata
///   7. `[writable]` pump_creator_vault
///   8. `[]` event_authority
///   9. `[]` program
#[derive(Clone, Debug)]
pub struct TransferCreatorFeesToPumpCpiBuilder<'a, 'b> {
    instruction: Box<TransferCreatorFeesToPumpCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> TransferCreatorFeesToPumpCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(TransferCreatorFeesToPumpCpiBuilderInstruction {
            __program: program,
            wsol_mint: None,
            token_program: None,
            system_program: None,
            associated_token_program: None,
            coin_creator: None,
            coin_creator_vault_authority: None,
            coin_creator_vault_ata: None,
            pump_creator_vault: None,
            event_authority: None,
            program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }

    /// Pump Canonical Pool are quoted in wSOL
    #[inline(always)]
    pub fn wsol_mint(&mut self, wsol_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.wsol_mint = Some(wsol_mint);
        self
    }

    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }

    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }

    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.associated_token_program = Some(associated_token_program);
        self
    }

    #[inline(always)]
    pub fn coin_creator(
        &mut self,
        coin_creator: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.coin_creator = Some(coin_creator);
        self
    }

    #[inline(always)]
    pub fn coin_creator_vault_authority(
        &mut self,
        coin_creator_vault_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.coin_creator_vault_authority = Some(coin_creator_vault_authority);
        self
    }

    #[inline(always)]
    pub fn coin_creator_vault_ata(
        &mut self,
        coin_creator_vault_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.coin_creator_vault_ata = Some(coin_creator_vault_ata);
        self
    }

    #[inline(always)]
    pub fn pump_creator_vault(
        &mut self,
        pump_creator_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pump_creator_vault = Some(pump_creator_vault);
        self
    }

    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }

    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }

    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult { self.invoke_signed(&[]) }

    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = TransferCreatorFeesToPumpCpi {
            __program: self.instruction.__program,

            wsol_mint: self.instruction.wsol_mint.expect("wsol_mint is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            associated_token_program: self
                .instruction
                .associated_token_program
                .expect("associated_token_program is not set"),

            coin_creator: self
                .instruction
                .coin_creator
                .expect("coin_creator is not set"),

            coin_creator_vault_authority: self
                .instruction
                .coin_creator_vault_authority
                .expect("coin_creator_vault_authority is not set"),

            coin_creator_vault_ata: self
                .instruction
                .coin_creator_vault_ata
                .expect("coin_creator_vault_ata is not set"),

            pump_creator_vault: self
                .instruction
                .pump_creator_vault
                .expect("pump_creator_vault is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct TransferCreatorFeesToPumpCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    wsol_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    coin_creator: Option<&'b solana_account_info::AccountInfo<'a>>,
    coin_creator_vault_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    coin_creator_vault_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    pump_creator_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
