//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};
use solana_pubkey::Pubkey;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapWithFeesCpiEvent {
    pub order_id: u64,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub source_mint: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub destination_mint: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub source_token_account_owner: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub destination_token_account_owner: Pubkey,
    pub source_token_change: u64,
    pub destination_token_change: u64,
    pub commission_direction: bool,
    pub commission_rate: u32,
    pub commission_amount: u64,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub commission_account: Pubkey,
    pub platform_fee_rate: u16,
    pub platform_fee_amount: u64,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub platform_fee_account: Pubkey,
    pub trim_rate: u8,
    pub trim_amount: u64,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub trim_account: Pubkey,
}

impl SwapWithFeesCpiEvent {
    /// CPI log prefix for self CPI events (Anchor standard)
    pub const CPI_LOG_PREFIX: [u8; 8] = [0xe4, 0x45, 0xa5, 0x2e, 0x51, 0xcb, 0x9a, 0x1d];
    /// SwapWithFeesCpiEvent discriminator bytes (from IDL)
    pub const DISCRIMINATOR: [u8; 8] = [0xbd, 0x61, 0x43, 0x0c, 0x25, 0xd1, 0xf7, 0x1d];

    /// Parse from inner instruction data with CPI log prefix
    pub fn from_inner_instruction_data(data: &[u8]) -> Option<Self> {
        if !data.starts_with(&Self::CPI_LOG_PREFIX) {
            return None;
        }

        let remaining_data = &data[8..];

        if !remaining_data.starts_with(&Self::DISCRIMINATOR) {
            return None;
        }

        Self::try_from_slice(&remaining_data[8..]).ok()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_discriminator_constant() {
        assert_eq!(SwapWithFeesCpiEvent::DISCRIMINATOR, [
            0xbd, 0x61, 0x43, 0x0c, 0x25, 0xd1, 0xf7, 0x1d
        ]);
    }

    #[test]
    fn test_parse_real_inner_instruction_data() {
        // Real inner instruction data from OKX DEX V2 swap transaction
        // Transaction: 2dPSizLSx2753FjAbKybupodyUBXEu9ksZMdqEW2iNRVWE3CXqWzFfCbawqjHaL78fa4wSHseQyhFWLMkxNd1zVD
        let hex_data = "e445a52e51cb9a1dbd61430c25d1f71dfd9a010000000000c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d610876fea7f49823fc141c8b34aa050b4e93cec310d592102bc0842e53ad6ee2ff5c0a9c0f8cef36986a49152d89e0e79b466817a8dfe964d85f9b473c0bf42a425c0a9c0f8cef36986a49152d89e0e79b466817a8dfe964d85f9b473c0bf42a4200c2eb0b00000000c145ae35230000000120b38100a0f0190000000000fe8ed5ee9a4ec57c494ec596d476c2291996450f16f435a939dc47c7170bd5cc00000000000000000000000000000000000000000000000000000000000000000000000000000000000032000000000000000022d88985f7fd6122556cb7781034be64650e8b956b047a7a92b607d37fc4baa0";

        let data = hex::decode(hex_data).expect("Failed to decode hex");
        let result = SwapWithFeesCpiEvent::from_inner_instruction_data(&data);
        assert!(result.is_some());

        let event = result.unwrap();
        assert_eq!(event.order_id, 105213);
        assert_eq!(event.source_token_change, 200000000); // 200 USDC
        assert_eq!(event.destination_token_change, 151224468929);
    }
}
