//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};

/// Accounts.
#[derive(Debug)]
pub struct BuyExactSolIn {
    pub global: solana_pubkey::Pubkey,

    pub fee_recipient: solana_pubkey::Pubkey,

    pub mint: solana_pubkey::Pubkey,

    pub bonding_curve: solana_pubkey::Pubkey,

    pub associated_bonding_curve: solana_pubkey::Pubkey,

    pub associated_user: solana_pubkey::Pubkey,

    pub user: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub token_program: solana_pubkey::Pubkey,

    pub creator_vault: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyExactSolInInstructionData {
    discriminator: [u8; 8],
}

impl BuyExactSolInInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [56, 252, 116, 8, 158, 223, 205, 95],
        }
    }
}

impl Default for BuyExactSolInInstructionData {
    fn default() -> Self { Self::new() }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyExactSolInInstructionArgs {
    pub spendable_sol_in: u64,
    pub min_tokens_out: u64,
}
