//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};
use solana_pubkey::Pubkey;

/// ix_name: "buy" | "buy_exact_quote_in"
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyEvent {
    pub timestamp: i64,
    pub base_amount_out: u64,
    pub max_quote_amount_in: u64,
    pub user_base_token_reserves: u64,
    pub user_quote_token_reserves: u64,
    pub pool_base_token_reserves: u64,
    pub pool_quote_token_reserves: u64,
    pub quote_amount_in: u64,
    pub lp_fee_basis_points: u64,
    pub lp_fee: u64,
    pub protocol_fee_basis_points: u64,
    pub protocol_fee: u64,
    pub quote_amount_in_with_lp_fee: u64,
    pub user_quote_amount_in: u64,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub pool: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user_base_token_account: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user_quote_token_account: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub protocol_fee_recipient: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub protocol_fee_recipient_token_account: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub coin_creator: Pubkey,
    pub coin_creator_fee_basis_points: u64,
    pub coin_creator_fee: u64,
    pub track_volume: bool,
    pub total_unclaimed_tokens: u64,
    pub total_claimed_tokens: u64,
    pub current_sol_volume: u64,
    pub last_update_timestamp: i64,
    pub min_base_amount_out: u64,
    pub ix_name: String,
}

// Constants for parsing buy events from CPI logs
pub const BUY_EVENT_DISCRIMINATOR: [u8; 8] = [0x67, 0xf4, 0x52, 0x1f, 0x2c, 0xf5, 0x77, 0x77];
pub const BUY_EVENT_CPI_LOG_PREFIX: [u8; 8] = [0xe4, 0x45, 0xa5, 0x2e, 0x51, 0xcb, 0x9a, 0x1d];

/// BuyEventBaseVersion only contains the first 304 bytes of data for forward compatibility.
/// This allows parsing old version events that don't have extra fields like coin_creator.
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyEventBaseVersion {
    pub timestamp: i64,                              // 8 bytes
    pub base_amount_out: u64,                        // 8 bytes
    pub max_quote_amount_in: u64,                    // 8 bytes
    pub user_base_token_reserves: u64,               // 8 bytes
    pub user_quote_token_reserves: u64,              // 8 bytes
    pub pool_base_token_reserves: u64,               // 8 bytes
    pub pool_quote_token_reserves: u64,              // 8 bytes
    pub quote_amount_in: u64,                        // 8 bytes
    pub lp_fee_basis_points: u64,                    // 8 bytes
    pub lp_fee: u64,                                 // 8 bytes
    pub protocol_fee_basis_points: u64,              // 8 bytes
    pub protocol_fee: u64,                           // 8 bytes
    pub quote_amount_in_with_lp_fee: u64,            // 8 bytes
    pub user_quote_amount_in: u64,                   // 8 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub pool: Pubkey,                                // 32 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user: Pubkey,                                // 32 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user_base_token_account: Pubkey,             // 32 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub user_quote_token_account: Pubkey,            // 32 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub protocol_fee_recipient: Pubkey,              // 32 bytes
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub protocol_fee_recipient_token_account: Pubkey, // 32 bytes
    // Total: 304 bytes
    // Extra fields (coin_creator, etc.) are ignored - we only parse base fields
}

impl BuyEventBaseVersion {
    /// Parse buy event from inner instruction data (CPI log)
    pub fn from_inner_instruction_data(data: &[u8]) -> Option<Self> {
        // Check for CPI log prefix
        if data.len() < 8 || &data[..8] != &BUY_EVENT_CPI_LOG_PREFIX {
            return None;
        }
        let event_data = &data[8..];

        // Check for event discriminator
        if event_data.len() < 8 || &event_data[..8] != &BUY_EVENT_DISCRIMINATOR {
            return None;
        }
        let buy_event_data = &event_data[8..];

        // Parse base version (first 304 bytes) for forward compatibility
        if buy_event_data.len() >= 304 {
            if let Ok(event) = BuyEventBaseVersion::try_from_slice(&buy_event_data[..304]) {
                return Some(event);
            }
        }
        None
    }
}
