//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum PumpAmmError {
    /// 6000 -
    #[error("")]
    FeeBasisPointsExceedsMaximum = 0x1770,
    /// 6001 -
    #[error("")]
    ZeroBaseAmount = 0x1771,
    /// 6002 -
    #[error("")]
    ZeroQuoteAmount = 0x1772,
    /// 6003 -
    #[error("")]
    TooLittlePoolTokenLiquidity = 0x1773,
    /// 6004 -
    #[error("")]
    ExceededSlippage = 0x1774,
    /// 6005 -
    #[error("")]
    InvalidAdmin = 0x1775,
    /// 6006 -
    #[error("")]
    UnsupportedBaseMint = 0x1776,
    /// 6007 -
    #[error("")]
    UnsupportedQuoteMint = 0x1777,
    /// 6008 -
    #[error("")]
    InvalidBaseMint = 0x1778,
    /// 6009 -
    #[error("")]
    InvalidQuoteMint = 0x1779,
    /// 6010 -
    #[error("")]
    InvalidLpMint = 0x177a,
    /// 6011 -
    #[error("")]
    AllProtocolFeeRecipientsShouldBeNonZero = 0x177b,
    /// 6012 -
    #[error("")]
    UnsortedNotUniqueProtocolFeeRecipients = 0x177c,
    /// 6013 -
    #[error("")]
    InvalidProtocolFeeRecipient = 0x177d,
    /// 6014 -
    #[error("")]
    InvalidPoolBaseTokenAccount = 0x177e,
    /// 6015 -
    #[error("")]
    InvalidPoolQuoteTokenAccount = 0x177f,
    /// 6016 -
    #[error("")]
    BuyMoreBaseAmountThanPoolReserves = 0x1780,
    /// 6017 -
    #[error("")]
    DisabledCreatePool = 0x1781,
    /// 6018 -
    #[error("")]
    DisabledDeposit = 0x1782,
    /// 6019 -
    #[error("")]
    DisabledWithdraw = 0x1783,
    /// 6020 -
    #[error("")]
    DisabledBuy = 0x1784,
    /// 6021 -
    #[error("")]
    DisabledSell = 0x1785,
    /// 6022 -
    #[error("")]
    SameMint = 0x1786,
    /// 6023 -
    #[error("")]
    Overflow = 0x1787,
    /// 6024 -
    #[error("")]
    Truncation = 0x1788,
    /// 6025 -
    #[error("")]
    DivisionByZero = 0x1789,
    /// 6026 -
    #[error("")]
    NewSizeLessThanCurrentSize = 0x178a,
    /// 6027 -
    #[error("")]
    AccountTypeNotSupported = 0x178b,
    /// 6028 -
    #[error("")]
    OnlyCanonicalPumpPoolsCanHaveCoinCreator = 0x178c,
    /// 6029 -
    #[error("")]
    InvalidAdminSetCoinCreatorAuthority = 0x178d,
    /// 6030 -
    #[error("")]
    StartTimeInThePast = 0x178e,
    /// 6031 -
    #[error("")]
    EndTimeInThePast = 0x178f,
    /// 6032 -
    #[error("")]
    EndTimeBeforeStartTime = 0x1790,
    /// 6033 -
    #[error("")]
    TimeRangeTooLarge = 0x1791,
    /// 6034 -
    #[error("")]
    EndTimeBeforeCurrentDay = 0x1792,
    /// 6035 -
    #[error("")]
    SupplyUpdateForFinishedRange = 0x1793,
    /// 6036 -
    #[error("")]
    DayIndexAfterEndIndex = 0x1794,
    /// 6037 -
    #[error("")]
    DayInActiveRange = 0x1795,
    /// 6038 -
    #[error("")]
    InvalidIncentiveMint = 0x1796,
    /// 6039 - buy: Not enough quote tokens to cover for fees.
    #[error("buy: Not enough quote tokens to cover for fees.")]
    BuyNotEnoughQuoteTokensToCoverFees = 0x1797,
    /// 6040 - buy: slippage - would buy less tokens than expected min_base_amount_out
    #[error("buy: slippage - would buy less tokens than expected min_base_amount_out")]
    BuySlippageBelowMinBaseAmountOut = 0x1798,
    /// 6041 -
    #[error("")]
    MayhemModeDisabled = 0x1799,
    /// 6042 -
    #[error("")]
    OnlyPumpPoolsMayhemMode = 0x179a,
    /// 6043 -
    #[error("")]
    MayhemModeInDesiredState = 0x179b,
    /// 6044 -
    #[error("")]
    NotEnoughRemainingAccounts = 0x179c,
    /// 6045 -
    #[error("")]
    InvalidSharingConfigBaseMint = 0x179d,
    /// 6046 -
    #[error("")]
    InvalidSharingConfigCoinCreator = 0x179e,
    /// 6047 - coin creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead
    #[error(
        "coin creator has been migrated to sharing config, use \
         pump_fees::reset_fee_sharing_config instead"
    )]
    CoinCreatorMigratedToSharingConfig = 0x179f,
    /// 6048 - creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead
    #[error(
        "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees \
         instead"
    )]
    CreatorVaultMigratedToSharingConfig = 0x17a0,
}

impl From<PumpAmmError> for solana_program_error::ProgramError {
    fn from(e: PumpAmmError) -> Self { solana_program_error::ProgramError::Custom(e as u32) }
}
